with open("NOMI_GoogleAppsScript.js", "a") as f:
    f.write("\n\n// -------------------------------------------------------\n")
    f.write("// RECORDATORIOS AUTOMÁTICOS\n")
    f.write("// -------------------------------------------------------\n\n")
    f.write('const FRONTEND_APP_URL = "https://nomi-app-web.vercel.app/metadata"; // <-- SI USAS OTRA URL EN PRODUCCIÓN, CÁMBIALA AQUÍ\n\n')
    
    f.write("function sendMorningReminders() {\n")
    f.write("  const doc = SpreadsheetApp.openById(MASTER_SHEET_ID);\n")
    f.write("  const usersSheet = doc.getSheetByName(TAB_REGISTRO);\n")
    f.write("  if (!usersSheet) return;\n  \n")
    f.write("  const data = usersSheet.getDataRange().getValues();\n")
    f.write("  for (let i = 1; i < data.length; i++) {\n")
    f.write("    const nickname = data[i][2];\n")
    f.write("    const email = data[i][3];\n")
    f.write("    if (!email) continue;\n    \n")
    f.write("    const subject = `${APP_NAME} — ¡Hora de tu test (Inicio de Jornada)!`;\n")
    f.write("    const htmlBody = `\n")
    f.write("      <div style=\"font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 560px; margin: 0 auto; background: #fff; padding: 40px 32px;\">\n")
    f.write("        <h1 style=\"font-size: 24px; font-weight: 900; color: #000; margin: 0 0 16px;\">Buen día, ${nickname}</h1>\n")
    f.write("        <p style=\"font-size: 15px; color: #555; margin: 0 0 20px;\">Es hora de registrar tu nivel de fatiga y voz al <strong>inicio de la jornada (Activo)</strong>.</p>\n")
    f.write("        <div style=\"text-align: center; margin-bottom: 32px; margin-top: 32px;\">\n")
    f.write("          <a href=\"${FRONTEND_APP_URL}\" style=\"display: inline-block; background: #000; color: #fff; text-decoration: none; font-size: 16px; font-weight: 800; padding: 16px 40px; border-radius: 12px;\">Comenzar test ahora</a>\n")
    f.write("        </div>\n")
    f.write("      </div>\n")
    f.write("    `;\n")
    f.write("    try {\n")
    f.write("      GmailApp.sendEmail(email, subject, '', { htmlBody, name: FROM_NAME });\n")
    f.write("    } catch (e) {}\n")
    f.write("  }\n")
    f.write("}\n\n")

    f.write("function sendEveningReminders() {\n")
    f.write("  const doc = SpreadsheetApp.openById(MASTER_SHEET_ID);\n")
    f.write("  const usersSheet = doc.getSheetByName(TAB_REGISTRO);\n")
    f.write("  if (!usersSheet) return;\n  \n")
    f.write("  const data = usersSheet.getDataRange().getValues();\n")
    f.write("  for (let i = 1; i < data.length; i++) {\n")
    f.write("    const nickname = data[i][2];\n")
    f.write("    const email = data[i][3];\n")
    f.write("    if (!email) continue;\n    \n")
    f.write("    const subject = `${APP_NAME} — ¡Hora de tu test (Fin de Jornada)!`;\n")
    f.write("    const htmlBody = `\n")
    f.write("      <div style=\"font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 560px; margin: 0 auto; background: #fff; padding: 40px 32px;\">\n")
    f.write("        <h1 style=\"font-size: 24px; font-weight: 900; color: #000; margin: 0 0 16px;\">Buenas tardes, ${nickname}</h1>\n")
    f.write("        <p style=\"font-size: 15px; color: #555; margin: 0 0 20px;\">Es hora de registrar tu nivel de fatiga y voz al <strong>fin de la jornada (Cansado)</strong>.</p>\n")
    f.write("        <div style=\"text-align: center; margin-bottom: 32px; margin-top: 32px;\">\n")
    f.write("          <a href=\"${FRONTEND_APP_URL}\" style=\"display: inline-block; background: #000; color: #fff; text-decoration: none; font-size: 16px; font-weight: 800; padding: 16px 40px; border-radius: 12px;\">Comenzar test ahora</a>\n")
    f.write("        </div>\n")
    f.write("      </div>\n")
    f.write("    `;\n")
    f.write("    try {\n")
    f.write("      GmailApp.sendEmail(email, subject, '', { htmlBody, name: FROM_NAME });\n")
    f.write("    } catch (e) {}\n")
    f.write("  }\n")
    f.write("}\n\n")
    
    f.write("function setupDailyTriggers() {\n")
    f.write("  // Eliminar triggers anteriores de estas funciones para no duplicar\n")
    f.write("  const triggers = ScriptApp.getProjectTriggers();\n")
    f.write("  for (let i = 0; i < triggers.length; i++) {\n")
    f.write("    const handler = triggers[i].getHandlerFunction();\n")
    f.write("    if (handler === 'sendMorningReminders' || handler === 'sendEveningReminders') {\n")
    f.write("      ScriptApp.deleteTrigger(triggers[i]);\n")
    f.write("    }\n")
    f.write("  }\n\n")
    f.write("  // Crear trigger para las 10 AM (aprox)\n")
    f.write("  ScriptApp.newTrigger('sendMorningReminders')\n")
    f.write("      .timeBased()\n")
    f.write("      .atHour(10)\n")
    f.write("      .everyDays(1)\n")
    f.write("      .create();\n\n")
    f.write("  // Crear trigger para las 19 PM (aprox)\n")
    f.write("  ScriptApp.newTrigger('sendEveningReminders')\n")
    f.write("      .timeBased()\n")
    f.write("      .atHour(19)\n")
    f.write("      .everyDays(1)\n")
    f.write("      .create();\n")
    f.write("}\n")
